config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  root 'zadankai#home'
  get 'zadankai/about'
  get 'zadankai/term'
  get 'zadankai/privacy'

  get 'projects/readyfor'
  get 'projects/new'

  resources :projects do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
    resources :conferences do
      resources :opinions
    end
  end

  resources :relationships, only: [:create, :destroy]

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users, except: [:index]
  resource :contacts, only: [:new, :create]

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  has_many :opinions

  validates :title, :description, presence: true
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new, :create, :show, :destroy, :edit, :update, :destroy]
    before_action :conference_owner, only: [:edit, :update, :destroy]

    require 'date'

    def index
        @project = Project.find(params[:project_id])
        redirect_to @project
    end

    def new
        @project = Project.find(params[:project_id])
        @conference = Conference.new

    end

    def create
        @project = Project.find(params[:project_id])
        @conference = @project.conferences.build(conference_params)
        if @conference.save
          flash[:success] = "座談会を作成しました！"
          redirect_to project_path(@project)
        else
          render 'new'
        end
    end

    def show
        if Project.find_by(:id => params[:project_id]) == nil
            redirect_to root_url
        else
            @project = Project.find_by(:id => params[:project_id])
        end

        if @conference = Conference.find_by(:id => params[:id]) == nil
            redirect_to @project
        else
            @conference = Conference.find(params[:id])
            @conference_title = @conference.title
        end


    end

    def edit
        @conferences = Conference.all
        @project = Project.find(params[:project_id])
        @conference = @project.conferences.find(params[:id])

    end

    def update
        @project = Project.find(params[:project_id])
        @conference = Conference.find(params[:id])
        if @conference.update(edit_conference_params)
          flash[:success] = "座談会情報を更新しました！"
          redirect_to @project
        else
          render 'edit'
        end
    end

    def destroy
        @conference = current_user.conferences.find_by(id: params[:id])
        return redirect_to root_url if @conference.nil?
        @conference.destroy
        flash[:success] = "この会議室は削除しました"
        redirect_to conferences_path
    end


    private

    def conference_params
        params.require(:conference).permit(:title, :description, :youtube_url, :conf_date)
    end

    def edit_conference_params
        params.require(:conference).permit(:title, :description, :youtube_url, :conf_date)
    end

    def conference_owner
        @project = Project.find(params[:project_id])
        @conference = Conference.find(params[:id])

        unless @project.user_id == current_user.id
          flash[:notice] = 'Access denied as you are not owner of this project'
          redirect_to projects_path
        end
    end

end

app/helpers/conferences_helper.rb
module ConferencesHelper
  def embed(youtube_url)
        @project = Project.find(params[:project_id])
        @conference = @project.conferences.find(params[:conference_id])
    if @conference.youtube_url.present?
        youtube_id = youtube_url.split("=").last
        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end
  end
end

app/views/conferences/edit.html.erb
<h1 style="text-align: center;">「<%= @conference.title %>」の内容を修正する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form">
    <%= simple_form_for([@project,@conference]) do |f| %>
    <%= f.error_notification %>
    <div class="field">
      <%= f.input :title, label: 'タイトル', error: 'タイトルは必須です。', :placeholder => "タイトルをご記入ください" %>
      <%= f.label :youtube_url, "Youtube動画 URL" %>
      <%= f.text_field :youtube_url, :placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" ,class: "form-control" %></br>
      <%= f.label :conf_date, "ざだんかい終了予定日" %>
      <div class='input-group date datepicker form-horizontal'>
      <%= f.text_field :conf_date, :placeholder => "(例)2015-01-01-12:00", class: 'form-control datepicker' %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div><br/>
      <%= f.label :description, "詳細内容", class: 'control-label' %>
      <%= f.cktext_area :description, class: 'form-control' %></br>
      <%= f.submit "ざだんかいを更新!", class: "btn btn-large btn-primary form-control" %>

    </div>
<% end %>
</div>

app/views/conferences/index.html.erb
<div class="container">
  <h1>座談会ズ</h1>
  <div>
    <% if @project.conferences.present? %>
      <% @project.conferences.each do |conference| %>
        <%= link_to conference.title, project_conference_path(@project, conference) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/conferences/new.html.erb
<h1 style="text-align: center;">座談会をひらく</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form">
    <%= render 'shared/conference_form' %>
  </div>
</div>
<script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                });
            });
</script>

app/views/conferences/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@project.project_name%>">
  <meta name="description" content="<%=@project.project_name %>に関する情報です。この商品を欲しい人、持ってる人を表示しています">
<% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <%  %>
    </div>
    <div class= "col-sm-8">
      <div class="title">
        <h2><%= @conference.title %></h2>
      </div>
      <% if @conference.youtube_url.present? %>
        <div class= "youtube-container">
          <%= embed(@conference.youtube_url) %>
        </div>
      <% else %>
        <% # %>
      <% end %>
      <div>
        <h3>内容</h3>
        <%== @conference.description %>
      </div><br/>
      <div>
        <% if current_user == @project.user && current_user != nil %>
            <%= link_to "座談会内容の編集", edit_project_conference_path(@project,@conference), class: "btn btn-large btn-default" %>
        <% end %>
      </div><br/>

      <section class="comment_form">
          <%= render 'shared/opinion_form' %>
      </section>
      <h3>コメント一覧 (<%= @conference.opinions.count %>)</h3>
      <% if @conference.opinions.count == 0 %>
        <p>現在コメントはありません。</p>
      <% end %>
        <% if @conference.opinions.present? %>
        <% @conference.opinions.order("created_at asc").each do |opinion| %>
          <% if opinion.opinion_user == @project.user.username %>
            <div class="comment2-1">
              <div class="imgL">
                <% if opinion.remote_avatar != nil %>
                  <p><%= image_tag(opinion.remote_avatar , alt: opinion.opinion_user) %><br/>
                  <%= opinion.opinion_user %></p>
              <% else %>
                  <p><%= image_tag(opinion.avatar , class: "icon_image", alt: opinion.opinion_user) %>
                  <%= opinion.opinion_user %></p>
              <% end %>
              </div>
              <div class="commentContents">  
                <p><%= simple_format opinion.body %></p>  
                <p class="data"><%= opinion.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                <% if current_user.username == opinion.opinion_user%>
                    <%= link_to "編集", edit_project_conference_opinion_path(@project, @conference, opinion), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_conference_opinion_path(@project, @conference, opinion), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                <% end %>
              <% end %>
                <!--/ .commentContents-->
              </div>  
            </div><!-- .comment2-1 -->
          <% else %>
            <div class="comment1-1">
              <div class="imgL">
                <% if opinion.remote_avatar != nil %>
                  <p><%= image_tag(opinion.remote_avatar , alt: opinion.opinion_user) %><br/>
                  <%= opinion.opinion_user %></p>
              <% else %>
                  <p><%= image_tag(opinion.avatar , class: "icon_image", alt: opinion.opinion_user) %>
                  <%= opinion.opinion_user %></p>
              <% end %>
              </div>
              <div class="commentContents">  
                <p><%= simple_format opinion.body %></p>  
                <p class="data"><%= opinion.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                <% if current_user.username == opinion.opinion_user%>
                    <%= link_to "編集", edit_project_conference_opinion_path(@project, @conference, opinion), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_conference_opinion_path(@project, @conference, opinion), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                <% end %>
              <% end %>
                <!--/ .commentContents-->
              </div>  
            </div><!-- .comment1-1 -->
          <% end %>
      <% end %>
      <% end %>
      
      <div class="project-button">
        <% if current_user == @conference.user %>
            <%= link_to "座談会にいく", project_conferences_path(@project, @conferece), class: "btn btn-large btn-primary" %>
            <%= link_to "この会議を削除", project_conferences_path(@project, @conferece), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
            <%= link_to "この会議の編集", edit_project_conference_path(@project, @conferece), class: "btn btn-large btn-danger" %>
        <% end %>
      </div>
      
    </div>  
    <div class="col-sm-2">
      
    </div>
  </div>
</div>