config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  root 'zadankai#home'
  get 'zadankai/about'
  get 'zadankai/term'
  get 'zadankai/privacy'

  get 'projects/readyfor'
  get 'projects/new'

  resources :projects do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
    resources :conferences do
      resources :opinions
    end
  end

  resources :relationships, only: [:create, :destroy]

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users, except: [:index]
  resource :contacts, only: [:new, :create]

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :conferences

  # validation
  validates :project_name, presence: true
  #relationships
  has_many :joining_relationships, class_name:  "Relationship",
                                    foreign_key: "joined_project_id",
                                    dependent:   :destroy
  has_many :joiner_users, through: :joining_relationships, source: :joiner_user

  mount_uploader :main_image, MainImageUploader

  paginates_per 12
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :project_owner, only: [:edit, :update, :destroy]
  before_action :category_set, only: [:new, :index, :edit]
  require 'date'

  def readyfor
    @title = "はじめよう！"
  end

  def index
    @projects = Project.order(created_at: :desc).page(params[:page])
    #検索
    @q = Project.page(params[:page]).search(params[:q])
    @searchedProjects = @q.result(distinct: true)

    @title = "プロジェクト一覧"


  end


  def new
    @project = Project.new
    @title = "新規プロジェクト作成"
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "新規プロジェクトを作成しました"
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
    @project_title = @project.project_name

    # 参加しているユーザー
    @users = @project.joiner_users.group('joiner_user_id')
    # 参加しているユーザーがいる場合はそのUserを取得
    if @users.any?
    @joinerUser = @project.joiner_users.find(@users)
    end

    # Time
    @d1 = Time.zone.now
    if @project.period_date.present?
    @d2 = (@project.period_date - @d1).to_i / 1.day
    end

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(edit_project_params)
      flash[:success] = "プロジェクト内容が更新されました"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = current_user.projects.find_by(id: params[:id])
    return redirect_to root_url if @project.nil?
    @project.destroy
    flash[:success] = "プロジェクトは削除されました"
    redirect_to projects_path
  end


  private

  def category_set
    @categories = ["アート","写真","プロダクト","スポーツ","お笑い","ファッション","ダンス","演劇・舞台","映像・映画","本・漫画","旅行","ビジネス","テクノロジー","社会貢献","その他"]
  end

  def project_params
    params
      .require(:project).permit(:project_name, :brand_name, :category, :main_image, :youtube_url, :description, :period_date)
  end

  def edit_project_params
    params.require(:project).permit(:project_name, :brand_name, :category, :main_image, :youtube_url, :description, :period_date)
  end

  #project のオーナーかどうか判断
  def project_owner
    @project = Project.find(params[:id])
    unless @project.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this project'
      redirect_to projects_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def embed(youtube_url)
    if @project.youtube_url.present?
        youtube_id = youtube_url.split("=").last
        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end
  end
end

app/views/projects/_conference_list.html.erb
    <h4>開かれてる座談会</h4>
    <% if @project.conferences.present? %>
      <div class="panel panel-info">
        <% @project.conferences.order("created_at desc").each do |conference| %>
          <div class="panel-heading">

          </div>
          <div class="panel-body">
            <p><%= link_to conference.title, project_conference_path(@project, conference) %></p>
            <% if conference.conf_date.present? %>
            <%if ((conference.conf_date - Time.zone.now).to_i / 1.day) >= 0 %>
              <h5 class="date">あと<strong><%= (conference.conf_date - Time.zone.now).to_i / 1.day %></strong>日</h5>
            <% else %>
            <h5 class="date"><strong>終了</strong></h5>
            <% end %>
          <% else %>
            <% # %>
          <% end %>
          </div>
        <% end %>
      </div>

    <% else current_user == @project.user %>
      <p>現在ひらかれている座談会はありません</p>
    <% end %>

app/views/projects/_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% projects.order("created_at desc").each do |project| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
            <% if project.main_image.present? %>
              <%= link_to image_tag(project.main_image.url , alt: project.project_name), project %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: project.project_name), project %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= project.project_name %>
            <!-- period date -->
            <%if ((project.period_date - Time.zone.now).to_i / 1.day) >= 0 %>
              <h5 class="date">あと<strong><%= (project.period_date - Time.zone.now).to_i / 1.day %></strong>日</h5>
            <% else %>
            <h5 class="date"><strong>終了</strong></h5>
            <% end %>
        </div>
        <div class="action clearfix">
          <%= link_to "#{project.category}", project , class: "btn-have btn btn-warning btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_list_users.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% projects.order("created_at desc").each do |project| %>
      <div class="item-box-mini">
        <div class="image">
          <div class="img-wrap">
            <% if project.main_image.present? %>
              <%= link_to image_tag(project.main_image.url , alt: project.project_name), project %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: project.project_name), project %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= project.project_name %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@project.project_name %>の編集">
  <meta name="description" content="<%=@project.project_name %>の情報の編集">
<% end %>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-project">
      <h3 style="text-align: center;">プロジェクト編集</h3>
      <%= simple_form_for(@project) do |f| %>
          <%= f.input :category, as: :select, collection: @categories, include_blank: '選択してください', label: 'カテゴリー', class: "form-control" %>

          <%= f.label :brand_name, "ブランド名" %>
          <%= f.text_field :brand_name, class: "form-control" %><br/>
          <%= f.input :project_name, label: 'プロジェクト名', class: "form-control" %>
          <%= f.label :period_date, "プロジェクト終了予定日" %>
          <div class='input-group date datepicker'>
          <%= f.text_field :period_date, :placeholder => "(例)2015-01-01-12:00", class: 'form-control datepicker' %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div><br/>

          <%= f.label :main_image, "メイン画像" %>
          <%= f.file_field :main_image, class: "form-control" %><br/>
          <%= f.label :youtube_url, "Youtube動画 URL" %>
          <%= f.text_field :youtube_url, :placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" ,class: "form-control" %><br/>

          <%= f.label :description, "プロジェクト詳細", class: 'control-label' %>
          <%= f.cktext_area :description, class: 'form-control' %><br/>
          <%= f.submit "プロジェクト情報の更新!", class: "btn btn-large btn-primary form-control" %>
      <% end %>
    </div>
</div>

app/views/projects/index.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="プロジェクトの一覧ページです。">
<% end %>

<div class="container">
  <!-- 検索フィールド -->
   <div class="search">
     <div class="search__icons">
        <span class="search__item search__item1">
          <%= search_form_for @q, html: { id: 'search__item_select', class: 'search__item_select' } do |f| %><br/>
          <div class="search__item_select">
          <!-- カテゴリーで検索 -->
            <%= f.select :category_cont, options_for_select(@categories), {include_blank: 'カテゴリーから検索'}, {class: "search__item_select"} %>
            <%= f.submit "検索する", class: "btn btn-sm btn-info" %>
            <% end %>
          </div>
        </span>

        <span class="search__item form__search">
          <%= search_form_for @q, html: { id: 'search__item_select', class: 'form__search' } do |f| %>
          <!-- start 特定の文字列で始まる商品名で検索 -->
            <%= f.search_field :project_name_cont, id:'keyword',class: "form-control form-control-inline", placeholder: "好きな言葉をここに" %>
            <%= f.submit "検索する", id:'search',class: "btn btn-sm btn-info" %>
          <% end %>
        </span>
      </div>
   </div>
</div><!-- container -->
 



  <% if @q == nil %>
<div class="container index-project">
    <div class="container">
      <%= render 'projects/list' , projects: @projects %>
      <%= paginate @projects, class: 'pagenation' %>
    </div>
  <% else %>
    <div class="container">
      <%= render 'projects/list' , projects: @searchedProjects %>
      <div class="pagenation"><%= paginate @searchedProjects %>
    <% end %>
    </div>
    </div>
</div>

app/views/projects/new.html.erb
<% content_for :head do %>
  <meta name="title" content="新規プロジェクト作成">
  <meta name="description" content="新しいプロジェクトを作成しよう">
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-project">
  <h3 style="text-align: center;">プロジェクトを作成する</h3>
    <%= simple_form_for(@project) do |f| %>
    <!-- error messages -->
    <%= f.error_notification %>
      <%= f.input :category, as: :select, collection: @categories, include_blank: '選択してください', label: 'カテゴリー' %></br>
      <%= f.input :brand_name, label: 'ブランド名', error: 'プロジェクト名は必須です' %><br/>

      <%= f.input :project_name,label: 'プロジェクト名', error: 'プロジェクト名は必須です。', :placeholder => "(例) 新感覚デニムを一からつくる！" %><br/>

      <%= f.label :period_date, "プロジェクト終了予定日" %>
      <div class='input-group date datepicker form-horizontal'>
        <%= f.text_field :period_date, :placeholder => "(例)2015-01-01-12:00", class: 'form-control datepicker' %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div><br/>

      <%= f.input :main_image, as: :file, label: 'メイン画像', class: "form-control" %><br/>

      <%= f.input :youtube_url, as: :url, label: 'Youtube動画 URL',:placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" %></br>

      <%= f.label :description, "プロジェクト詳細",  class: 'control-label' %>
      <%= f.cktext_area :description, class: 'form-control' %><br/>
      <%= f.submit "プロジェクトを投稿する！", class: "btn btn-large btn-primary form-control" %>

    <% end %>
  </div>
  <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                });
            });
  </script>
</div>

app/views/projects/readyfor.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="プロジェクトをはじめよう！">
<% end %>

<div id="ready-for-jumbotron">
    <div class="container">
      <h1 style="text-align: center;">Zadankai</h1>
      <p style="text-align: center;">ファンファンファン</p>
      <h3>How to start your own project?</h3><br/>
      <h2>⬇︎</h2>
    </div><!-- /.container -->
</div><!-- /.jumbotron -->

<div id="readyfor-contents" class="container">
  <h2>使い方はかんたん。<br/>
  プロジェクトを作成してスタートするだけ。</h2>
  <div class="row">
    <div class="col-md-4">
      <h4><span class="step">1</span> プロジェクトを作成</h4>
    </div>
    <div class="col-md-4">
      <h4><span class="step">2</span> 座談会を開催して、プロジェクトを創り上げていく。</h4>
    </div>
    <div class="col-md-4">
      <h4><span class="step">3</span> プロジェクト完了報告！</h4>
    </div>
  </div>
  <% if user_signed_in?  %>
    <h5><%= link_to "プロジェクトを作成する", projects_new_path, class: "btn btn-large btn-info" %></h5>
  <% else %>
    <h5><%= link_to "まずは新規会員登録する", new_user_registration_path, class: "post btn btn-large btn-info" %></h5>
  <% end %>
</div>
<div id="about" class="container">

</div>
<div id="about-zadankai">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <!-- 写真か何かを入れる -->
      </div>
      <div class="col-md-6">
        <h2>Zadankaiとは？</h2>
        <p>こんなものを創りたい。こんなイベントを企画したい。なにか楽しいことをしたい。<br/>
        そういったあなたの心の中にある思いを形にするお手伝いをしたい。<br/>
        そんな思いから、この「Zadankai」はスタートしました。<br/>
        気軽に心の中の想いをシェアして、それに賛同してくれる仲間（ファン）に出会い、企画を実現させる。<br/>
        どんどんアイデアをシェアしよう。そのアイデアをみんなで育てて実現させよう。<br/>
        </p>
      </div>

    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@project.project_name %>">
  <meta name="description" content="「<%= @project.project_name %>」に関する情報です">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-2 project-user-profile">
      <% if @project.brand_name.present? %>
        <h4><%= @project.brand_name %></h4>
      <% end %>
      <% if @project.user != nil %>
      <h4><%= @project.user.username %></h4>
        <!-- image -->
        <% if @project.user.remote_avatar != nil %>
          <%= link_to image_tag(@project.user.remote_avatar , alt: @project.user.username), user_path(@project.user) %>
        <% elsif @project.user.avatar.url != nil %>
          <%= link_to image_tag(@project.user.avatar.url , alt: @project.user.username), user_path(@project.user) %>
        <% else %>
          <%= link_to image_tag("/images/user.jpg" , alt: "No Image"), user_path(@project.user) %>
        <% end %>
      <% end %>
      <h5>プロジェクト完了予定日</h5>
      <% if @project.period_date.present? %>
        <h5><%= @project.period_date %></h5>
        <% if @d2 >= 0 %>
        <h5>終了まであと<strong><%= @d2 %></strong>日</h5>
        <% else %>
        <h5>終了</h5>
        <% end %>
      <% end %>
      <div>
        <% if current_user == @project.user && current_user != nil %>
            <%= link_to "プロジェクトの編集", edit_project_path(@project), class: "btn btn-large btn-default" %>
        <% end %>
      </div>
    </div>
    <div class= "col-sm-7">
      <div class="title">
       <!-- user join form -->
       <% if current_user != nil && current_user != @project.user %>
         <%= render 'users/join_form' %>
       <% end %>

        <h2><%= @project.project_name %></h2>
      </div>
      <% if @project.youtube_url.present? %>
        <div class= "youtube-container">
        <%= embed(@project.youtube_url) %>
        </div>
      <% else %>
        <%= image_tag(@project.main_image) %>
      <% end %><br/>

      <!-- facebook いいね -->
      <div class="fb-like" data-href="<%= "http://#{request.host+request.fullpath}" %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
        <h3>どんなプロジェクトなの？</h3>
        <%== @project.description %>
         <% if current_user != nil %>
      <section class="comment_form">
          <%= render 'shared/comment_form' %>
      </section>
      <% end %>
      <h3>コメント一覧 (<%= @project.comments.count %>)</h3>
      <% if @project.comments.count == 0 %>
        <p>現在コメントはありません。</p>
      <% end %>
        <% if @project.comments.present? %>
        <% @project.comments.order("created_at asc").each do |comment| %>
        <!-- コメントがプロジェクトオーナーの場合は右表示 -->
          <% if comment.commenter == @project.user.username %>
            <div class="comment2-1">
              <div class="imgL">
                <% if comment.remote_avatar != nil %>
                  <p><%= image_tag(comment.remote_avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% else %>
                  <p><%= image_tag(comment.avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% end %>
              </div>
              <div class="commentContents">
                <p><%= simple_format comment.body %></p>
                <p class="data"><%= comment.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                  <% if current_user.username == comment.commenter%>
                    <%= link_to "編集", edit_project_comment_path(@project, comment), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_comment_path(@project, comment), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                  <% end %>
                <% end %>
                <!--/ .commentContents-->
              </div>
            </div><!-- .comment1-1 -->
          <% else %><!-- その他の人は左表示 -->
            <div class="comment1-1">
              <div class="imgL">
                <% if comment.remote_avatar != nil %>
                  <p><%= image_tag(comment.remote_avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% else %>
                  <p><%= image_tag(comment.avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% end %>
              </div>
              <div class="commentContents">
                <p><%= simple_format comment.body %></p>
                <p class="data"><%= comment.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                  <% if current_user.username == comment.commenter%>
                    <%= link_to "編集", edit_project_comment_path(@project, comment), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_comment_path(@project, comment), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                  <% end %>
                <% end %>
                <!--/ .commentContents-->
              </div>
            </div><!-- .comment1-1 -->
          <% end %>
       <% end %>
       <% end %>
    </div>
    <div class="col-sm-3">
      <% if @users.any? %>
      <p>プロジェクトメンバー数: <strong><%= @users.length %></strong>人</p>

      <% end %>

      <% if current_user == @project.user && current_user != nil %>
      <div>
          <%= link_to "座談会を開催する！" , new_project_conference_path(@project),class: "btn btn-large btn-info" %>
      </div><br/>
      <% else %>
        <%  %>
      <% end %>

      <% if current_user != nil %>
        <% if @joinerUser != nil %>
          <% if @users.include? current_user %>
            <%= render 'conference_list' %>
          <% elsif current_user == @project.user %>
            <%= render 'conference_list' %>
          <% else %>
            <% # %>
          <% end %>
        <% elsif current_user == @project.user %>
          <%= render 'conference_list' %>
        <% else %>
          <% # %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>