config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  root 'zadankai#home'
  get 'zadankai/about'
  get 'zadankai/term'
  get 'zadankai/privacy'

  get 'projects/readyfor'
  get 'projects/new'

  resources :projects do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
    resources :conferences do
      resources :opinions
    end
  end

  resources :relationships, only: [:create, :destroy]

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users, except: [:index]
  resource :contacts, only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<ul class="navbar-nav">
  <li><%= link_to "Zadankaiとは？", zadankai_about_path, class: "link"  %> | <%= link_to "利用規約", zadankai_term_path, class: "link"  %> | <%= link_to "プライバシーポリシー", zadankai_privacy_path, class: "link"  %> | <%= link_to "お問い合わせ", new_contacts_path, class: "link" %></li><br/>
  <li>© <%= Date.today.year %> Zadanstyle.com All right reserved.</li>
</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <%= link_to "Zadankai", root_path, class: "navbar-brand", id: "brand-logo" %>
        <nav>
        <button class="navbar-toggle" data-toggle = "collapse" data-target = ".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav pull-right">
                <li>
                    <%= link_to "プロジェクトをはじめる", projects_readyfor_path %>
                </li>
                <li><%= link_to "プロジェクトを探す", projects_path %></li>
                <li><%= link_to "Zadankaiとは？", zadankai_about_path  %></li>
                 <% if user_signed_in? %>
                    <li>
                      <%= link_to "マイページ", user_path(current_user) %>
                    </li>
                    <li>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    <li>
                      <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
                    </li>
                    <li>
                      <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
                    </li>
                <% end %>
            </ul>
        </div>
        </nav>
    </div>

</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @project_title.present? %>
    <title><%= "#{@project_title} - Zadankai" %></title>
  <% elsif @userName.present? %>
    <title><%= "#{@userName} - Zadankai" %></title>
  <% elsif @conference_title.present? %>
    <title><%= "#{@conference_title} - Zadankai" %></title>
  <% elsif @title.present? %>
    <title><%= "#{@title} - Zadankai" %></title>
  <% else %>
    <title><%= 'Zadankai' %></title>
  <% end %>
  <!-- #meta information -->
  <%= yield :head %>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'application',  'Ckeditor.cdn_url' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= render partial: "layouts/header" %>

<%= render 'layouts/messages' %>

  <%= yield %>

<%= render partial: "layouts/footer" %>

 <!-- facebook javascript SDK -->
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1067987169925893',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.5&appId=1067987169925893";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>